// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj3Ckc3RwIzRnPZFwRYPHYtMlxACVyjA8',
    appId: '1:757980626508:web:9b1d334bcc311910d23ee9',
    messagingSenderId: '757980626508',
    projectId: 'home-hero-90faa',
    authDomain: 'home-hero-90faa.firebaseapp.com',
    storageBucket: 'home-hero-90faa.appspot.com',
    measurementId: 'G-TN4H91VBT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0bMzvHlUYaJkOUoh9L3njojcbBfUbjvA',
    appId: '1:757980626508:android:7143981883912e5dd23ee9',
    messagingSenderId: '757980626508',
    projectId: 'home-hero-90faa',
    storageBucket: 'home-hero-90faa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvSlCgovtPqjyZZnynlgDygdZHXQGVPk',
    appId: '1:757980626508:ios:9c832428728682add23ee9',
    messagingSenderId: '757980626508',
    projectId: 'home-hero-90faa',
    storageBucket: 'home-hero-90faa.appspot.com',
    iosBundleId: 'com.example.homeHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIvSlCgovtPqjyZZnynlgDygdZHXQGVPk',
    appId: '1:757980626508:ios:9c832428728682add23ee9',
    messagingSenderId: '757980626508',
    projectId: 'home-hero-90faa',
    storageBucket: 'home-hero-90faa.appspot.com',
    iosBundleId: 'com.example.homeHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj3Ckc3RwIzRnPZFwRYPHYtMlxACVyjA8',
    appId: '1:757980626508:web:82ab0cde28e5cdd2d23ee9',
    messagingSenderId: '757980626508',
    projectId: 'home-hero-90faa',
    authDomain: 'home-hero-90faa.firebaseapp.com',
    storageBucket: 'home-hero-90faa.appspot.com',
    measurementId: 'G-MGPMMRH29F',
  );
}
